CREATE TABLE IF NOT EXISTS t_user (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(128) NOT NULL,
    openid VARCHAR(64),
    role VARCHAR(20) DEFAULT 'USER',
    del_user BOOLEAN DEFAULT 0,
    del_time DATETIME,
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP
);
